### ISSUE TITLE
Static Version update to enable the uNav "Alerts" feature

### ISSUE THREAD

**Issue by ValPerrotte** [nys-its/universal-navigation#187]
On my dev server I see the yellow alert banner with a December 5. 2014 date.
When I place the same file on my staging server I no longer see the yellow bar.  

Chris Catalina is seeing the same yellow bar on the DMV dev server. 
http://nydmvdev.prod.acquia-sites.com/
 
Can you explain why we are still seeing this?

**Comment by gingerg** [comment]
Hi Val - I'm in the middle of implementing this on several sites myself - one quick thing to check - is your uNav code pointing to src="//static-assets.ny.gov/load_global_menu/ajax?iframe=true&xdiframe=YOURPATHHERE"

(just make sure it's not the C&T Dev site)

**Comment by ValPerrotte** [comment]
No, I am just putting the file in the site root. I am concerned that we are seeing different results on different servers.  I would assume that since there are no current alerts, that I would not see any yellow banner on dev.

**Comment by ValPerrotte** [comment]
I just saw Kevin Luddy's response to a question posted by Melissa Simpson and had an ah ha moment.  It was so long ago when we first tested this that I forgot I had changed the url on our dev server to point to the dev instance for the static banner.  Chris had the same issue.  We updated the url and it appears correctly. Thanks
