### ISSUE TITLE
error “Moment” is undefined.

### ISSUE THREAD

**Issue by tjcrommie** [nys-its/universal-navigation#193]
Subject: RE: Alert in U Nav
 
We are getting an error “Moment” is undefined.
 
In this function:
 
function anonymous(obj,_) {
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
with(obj||{}){
__p+='\n    <a href="'+
((__t=(emergency.link))==null?'':__t)+
'">\n        <p class="nygov-emergency-date-title">\n            <span class="icon-alert"></span>\n            <span class="nygov-emergency-date">\n                '+
((__t=(moment(emergency.update_date).format('[<strong>]MMMM D, YYYY[</strong>] | h:mm a z')))==null?'':__t)+
'\n            </span>\n            <span class="nygov-emergency-title">\n                '+
((__t=(emergency.title))==null?'':__t)+
'\n            </span>\n        </p>\n        <p class="nygov-emergency-description">\n            '+
((__t=(emergency.description))==null?'':__t)+
'\n            <span class="nygov-emergency-see-all">\n                '+
((__t=(emergency.link_label))==null?'':__t)+
'\n            </span>\n        </p>\n    </a>\n';
}
return __p;

**Comment by lukecharde** [comment]
@tjcrommie has this been resolved?

**Comment by tjcrommie** [comment]
Yes Closing,  We update the code from GitHub, the code that C&T provided was throwing the error, The new code is working.
