### ISSUE TITLE
Static Alerts not working on some 4th level domains

### ISSUE THREAD

**Issue by gingerg** [nys-its/universal-navigation#194]
Conversation in issue #192 has evolved into this new issue...

not displaying the alerts:

programs.governor.ny.gov/citizenconnects (xd_nygov.html in doc root)

GET http://programs.governor.ny.gov/xd_nygov.html?en=1&gn=0&host=http%3A%2F%2Fstatic-assets.ny.gov%2Fload_global_menu%2Fajax%3Fiframe%3Dtrue&height=283 404 (Not Found)ajax?iframe=true:263 (anonymous function)

** two of the domains with errors have been corrected. We continue to troubleshoot the CitizenConnects domain.

**Comment by tjcrommie** [comment]
We need to support four level domains, there are a lot of application and county level site with 4 levels, this is in compliance with NYS-P08-003 Domain Names for State Government Agencies (“program_name”.“agency_name”.ny.gov )

**Comment by lzuker** [comment]
This has been resolved on our end. It was actually a problem with our code. We had some ampersands in place of percentages after //static-assets.ny.gov/load_global_menu/ajax?iframe=true&xdiframe=(path to file). @gingerg can we close this?

**Comment by gingerg** [comment]
No. Continuing to troubleshoot the CitizenConnects domain issue.

**Comment by lzuker** [comment]
Sorry, my mistake.

**Comment by gingerg** [comment]
@lzuker found the issue, and has the static alerts banner working on CitizenConnects prod. Thanks, Leslie! :) Confirmed, and closing.
